SESSION 9 - Working with Date & Time DataTopics Covered:Converting strings to datetimepd.to_datetime()Extracting datetime componentsday, month, year,
weekday, quarterSetting datetime as indexResampling (daily, weekly, monthly)Handling timezone issuesCreating new time-based features



TASKS

In [1]:
import pandas as pd

In [52]:
import numpy as np


1. Given a list of delivery timestamps as strings (e.g., ['2024-06-01 14:30', '2024-06-02 09:15', '2024-06-03 20:45']), use pandas and pd.to_datetime() to convert them into datetime objects and print the result.

In [25]:
dataset = pd.read_csv("F:\Tops_assignment\Python_Library\datasets\ipl\matches.csv")

In [8]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   object
 2   city             1044 non-null   object
 3   date             1095 non-null   datetime64[ns]
 4   match_type       1095 non-null   object
 5   player_of_match  1090 non-null   object
 6   venue            1095 non-null   object
 7   team1            1095 non-null   object
 8   team2            1095 non-null   object
 9   toss_winner      1095 non-null   object
 10  toss_decision    1095 non-null   object
 11  winner           1090 non-null   object
 12  result           1095 non-null   object
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   object
 17  method           21 non-null     object
 18  umpire1          1095 non-null   object
 19  umpire2          1095 non-null   object
 20  date1            300 non-null    object
dtypes: datetime64[ns](1), float64(3), int64(1), object(16)
memory usage: 179.8+ KB

In [26]:
dataset["date"] = pd.to_datetime(dataset["date"])

In [28]:
list1 = ['2024-06-01 14:30', '2024-06-02 09:15', '2024-06-03 20:45']*100
dataset["date1"]= pd.DataFrame({"date1" : list1 })

In [ ]:
dataset[["date"], ["time"]] = pd.to_datetime(dataset["date1"]).str.split(" " ,expand = True)

# can you split only if the data is string not the date and time

AttributeError: Can only use .str accessor with string values!

In [29]:
dataset

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,...,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2,date1
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,2024-06-01 14:30
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,...,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri,2024-06-02 09:15
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,...,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar,2024-06-03 20:45
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,...,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper,2024-06-01 14:30
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,...,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan,2024-06-02 09:15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,1426307,2024,Hyderabad,2024-05-19,League,Abhishek Sharma,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Punjab Kings,Sunrisers Hyderabad,Punjab Kings,...,Sunrisers Hyderabad,wickets,4.0,215.0,20.0,N,NaN,Nitin Menon,VK Sharma,NaN
1091,1426309,2024,Ahmedabad,2024-05-21,Qualifier 1,MA Starc,"Narendra Modi Stadium, Ahmedabad",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,...,Kolkata Knight Riders,wickets,8.0,160.0,20.0,N,NaN,AK Chaudhary,R Pandit,NaN
1092,1426310,2024,Ahmedabad,2024-05-22,Eliminator,R Ashwin,"Narendra Modi Stadium, Ahmedabad",Royal Challengers Bengaluru,Rajasthan Royals,Rajasthan Royals,...,Rajasthan Royals,wickets,4.0,173.0,20.0,N,NaN,KN Ananthapadmanabhan,MV Saidharshan Kumar,NaN
1093,1426311,2024,Chennai,2024-05-24,Qualifier 2,Shahbaz Ahmed,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,...,Sunrisers Hyderabad,runs,36.0,176.0,20.0,N,NaN,Nitin Menon,VK Sharma,NaN
1094,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,...,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon,NaN

In [30]:
dataset["date1"] = pd.to_datetime(dataset["date1"])
dataset["date11"] = dataset["date1"].dt.date
dataset["time1"] = dataset["date1"].dt.time

dataset

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,...,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2,date1,date11,time1
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,2024-06-01 14:30:00,2024-06-01,14:30:00
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,...,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri,2024-06-02 09:15:00,2024-06-02,09:15:00
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,...,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar,2024-06-03 20:45:00,2024-06-03,20:45:00
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,...,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper,2024-06-01 14:30:00,2024-06-01,14:30:00
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,...,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan,2024-06-02 09:15:00,2024-06-02,09:15:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,1426307,2024,Hyderabad,2024-05-19,League,Abhishek Sharma,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Punjab Kings,Sunrisers Hyderabad,Punjab Kings,...,4.0,215.0,20.0,N,NaN,Nitin Menon,VK Sharma,NaT,NaT,NaT
1091,1426309,2024,Ahmedabad,2024-05-21,Qualifier 1,MA Starc,"Narendra Modi Stadium, Ahmedabad",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,...,8.0,160.0,20.0,N,NaN,AK Chaudhary,R Pandit,NaT,NaT,NaT
1092,1426310,2024,Ahmedabad,2024-05-22,Eliminator,R Ashwin,"Narendra Modi Stadium, Ahmedabad",Royal Challengers Bengaluru,Rajasthan Royals,Rajasthan Royals,...,4.0,173.0,20.0,N,NaN,KN Ananthapadmanabhan,MV Saidharshan Kumar,NaT,NaT,NaT
1093,1426311,2024,Chennai,2024-05-24,Qualifier 2,Shahbaz Ahmed,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,...,36.0,176.0,20.0,N,NaN,Nitin Menon,VK Sharma,NaT,NaT,NaT
1094,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,...,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon,NaT,NaT,NaT


2. Load a CSV file containing order dates from a Flipkart-style order history (column: 'order_date', format: 'YYYY-MM-DD HH:MM:SS'). Extract the year, month, and weekday for each order and add them as new columns in
the DataFrame.

In [36]:
dataset.info()
dataset["date11"] = pd.to_datetime(dataset["date11"])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   object
 2   city             1044 non-null   object
 3   date             1095 non-null   datetime64[ns]
 4   match_type       1095 non-null   object
 5   player_of_match  1090 non-null   object
 6   venue            1095 non-null   object
 7   team1            1095 non-null   object
 8   team2            1095 non-null   object
 9   toss_winner      1095 non-null   object
 10  toss_decision    1095 non-null   object
 11  winner           1090 non-null   object
 12  result           1095 non-null   object
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   object
 17  method           21 non-null     object
 18  umpire1          1095 non-null   object
 19  umpire2          1095 non-null   object
 20  date1            300 non-null    datetime64[ns]
 21  date11           300 non-null    object
 22  time1            300 non-null    object
dtypes: datetime64[ns](2), float64(3), int64(1), object(17)
memory usage: 196.9+ KB

In [37]:
dataset["year"] = dataset["date11"].dt.year
dataset["Month"] = dataset["date11"].dt.month
dataset["day"] = dataset["date11"].dt.day

dataset

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,...,super_over,method,umpire1,umpire2,date1,date11,time1,year,Month,day
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,N,NaN,Asad Rauf,RE Koertzen,2024-06-01 14:30:00,2024-06-01,14:30:00,2024.0,6.0,1.0
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,...,N,NaN,MR Benson,SL Shastri,2024-06-02 09:15:00,2024-06-02,09:15:00,2024.0,6.0,2.0
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,...,N,NaN,Aleem Dar,GA Pratapkumar,2024-06-03 20:45:00,2024-06-03,20:45:00,2024.0,6.0,3.0
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,...,N,NaN,SJ Davis,DJ Harper,2024-06-01 14:30:00,2024-06-01,14:30:00,2024.0,6.0,1.0
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,...,N,NaN,BF Bowden,K Hariharan,2024-06-02 09:15:00,2024-06-02,09:15:00,2024.0,6.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,1426307,2024,Hyderabad,2024-05-19,League,Abhishek Sharma,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Punjab Kings,Sunrisers Hyderabad,Punjab Kings,...,N,NaN,Nitin Menon,VK Sharma,NaT,NaT,NaT,NaN,NaN,NaN
1091,1426309,2024,Ahmedabad,2024-05-21,Qualifier 1,MA Starc,"Narendra Modi Stadium, Ahmedabad",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,...,N,NaN,AK Chaudhary,R Pandit,NaT,NaT,NaT,NaN,NaN,NaN
1092,1426310,2024,Ahmedabad,2024-05-22,Eliminator,R Ashwin,"Narendra Modi Stadium, Ahmedabad",Royal Challengers Bengaluru,Rajasthan Royals,Rajasthan Royals,...,N,NaN,KN Ananthapadmanabhan,MV Saidharshan Kumar,NaT,NaT,NaT,NaN,NaN,NaN
1093,1426311,2024,Chennai,2024-05-24,Qualifier 2,Shahbaz Ahmed,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,...,N,NaN,Nitin Menon,VK Sharma,NaT,NaT,NaT,NaN,NaN,NaN
1094,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,...,N,NaN,J Madanagopal,Nitin Menon,NaT,NaT,NaT,NaN,NaN,NaN


3. Set the 'order_date' column as the index of your DataFrame and use resampling to calculate the total number of orders placed each week.

        Hint: Use df.resample('W').size() after setting the datetime index.

# there are two ways one is changing the index of the dataframe and then the naother is that we are not changing the index but we are saying the resmaping that w=hih colun is date ad time

In [46]:
dataset.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,...,target_overs,super_over,method,umpire1,umpire2,date1,time1,year,Month,day
date11,,,,,,,,,,,,,,,,,,,,,
2024-06-01,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,20.0,N,NaN,Asad Rauf,RE Koertzen,2024-06-01 14:30:00,14:30:00,2024.0,6.0,1.0
2024-06-02,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,...,20.0,N,NaN,MR Benson,SL Shastri,2024-06-02 09:15:00,09:15:00,2024.0,6.0,2.0
2024-06-03,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,...,20.0,N,NaN,Aleem Dar,GA Pratapkumar,2024-06-03 20:45:00,20:45:00,2024.0,6.0,3.0
2024-06-01,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,...,20.0,N,NaN,SJ Davis,DJ Harper,2024-06-01 14:30:00,14:30:00,2024.0,6.0,1.0
2024-06-02,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,...,20.0,N,NaN,BF Bowden,K Hariharan,2024-06-02 09:15:00,09:15:00,2024.0,6.0,2.0

In [49]:
#dataset.set_index("date11" , inplace= True)
dataset.resample("W").size()

date11
2024-06-02    200
2024-06-09    100
dtype: int64

## without reindexing

In [50]:
dataset.resample("W" , on= "date1").size()

date1
2024-06-02    200
2024-06-09    100
dtype: int64


4. Suppose you have a DataFrame of Instagram posts with a 'posted_at' column in UTC. Convert these timestamps to 'Asia/Kolkata' timezone and display the first 5 converted times.

In [53]:

np.random.seed(42)

usernames = [
    "aman", "priya", "rahul", "neha", "jay",
    "simran", "rohit", "karan", "pooja", "vishal"
]

captions = [
    "Travel Diaries", "Gym Time", "Food Lover",
    "Weekend Vibes", "Nature Shot", "Coffee Break",
    "Work Mode", "Sunset Click", "Friends Forever",
    "New Adventure"
]

df = pd.DataFrame({
    "post_id": range(1001, 1101),
    "username": np.random.choice(usernames, 100),
    "caption": np.random.choice(captions, 100),
    "likes": np.random.randint(50, 5000, 100),
    "comments": np.random.randint(0, 500, 100),
    "posted_at": pd.to_datetime(
        np.random.choice(
            pd.date_range(
                start="2025-01-01",
                end="2025-03-31",
                freq="H",
                tz="UTC"
            ),
            100
        )
    )
})

print(df.head())
print(df.shape)

C:\Users\Dell\AppData\Local\Temp\ipykernel_49300\1518215223.py:23: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  pd.date_range(

   post_id username         caption  likes  comments                 posted_at
0     1001    rohit        Gym Time   1980         5 2025-03-08 11:00:00+00:00
1     1002     neha  Travel Diaries   3632        98 2025-01-01 04:00:00+00:00
2     1003    karan       Work Mode    658       379 2025-02-16 22:00:00+00:00
3     1004      jay       Work Mode   3322       232 2025-02-20 19:00:00+00:00
4     1005    rohit    Sunset Click   1197        36 2025-02-02 05:00:00+00:00
(100, 6)

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   post_id    100 non-null    int64
 1   username   100 non-null    object
 2   caption    100 non-null    object
 3   likes      100 non-null    int32
 4   comments   100 non-null    int32
 5   posted_at  100 non-null    datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](1), int32(2), int64(1), object(2)
memory usage: 4.0+ KB

In [56]:
df["time_zone_ist"] = df["posted_at"].dt.tz_convert("Asia/Kolkata")

In [58]:
df.head()

,post_id,username,caption,likes,comments,posted_at,time_zone_ist
0,1001,rohit,Gym Time,1980,5,2025-03-08 11:00:00+00:00,2025-03-08 16:30:00+05:30
1,1002,neha,Travel Diaries,3632,98,2025-01-01 04:00:00+00:00,2025-01-01 09:30:00+05:30
2,1003,karan,Work Mode,658,379,2025-02-16 22:00:00+00:00,2025-02-17 03:30:00+05:30
3,1004,jay,Work Mode,3322,232,2025-02-20 19:00:00+00:00,2025-02-21 00:30:00+05:30
4,1005,rohit,Sunset Click,1197,36,2025-02-02 05:00:00+00:00,2025-02-02 10:30:00+05:30


5. Create a new feature called 'is_weekend' in your DataFrame that marks True if an order was placed on Saturday or Sunday, and False otherwise.

        Constraint: Do not use any external libraries except pandas and numpy.

In [64]:
#df["is_weekend"] = df["time_zone_ist"].dt.weekday >= 5
#df["day"] = df["is_weekend"].dt.day_name()
df["day"] = df["time_zone_ist"].dt.day_name().isin(["Saturday" , "Sunday"])

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   post_id        100 non-null    int64
 1   username       100 non-null    object
 2   caption        100 non-null    object
 3   likes          100 non-null    int32
 4   comments       100 non-null    int32
 5   posted_at      100 non-null    datetime64[ns, UTC]
 6   time_zone_ist  100 non-null    datetime64[ns, Asia/Kolkata]
 7   is_weekend     100 non-null    bool
 8   day            100 non-null    bool
dtypes: bool(2), datetime64[ns, Asia/Kolkata](1), datetime64[ns, UTC](1), int32(2), int64(1), object(2)
memory usage: 5.0+ KB